---
# tasks file for glance
- name: "Create glance user"
  openstack.cloud.identity_user:
    auth: "{{ os_glance_cloud_auth }}"
    name: glance
    password: "{{ os_glance_ka_password }}"
    domain: default
    state: present
  no_log: true
  delegate_to: localhost
  become: false

- name: "Add glance user to project service with admin role"
  openstack.cloud.role_assignment:
    auth: "{{ os_glance_cloud_auth }}"
    user: glance
    role: admin
    project: service
    state: present
  delegate_to: localhost
  become: false

- name: "Make sure that the glance account has reader access to system-scope resources"
  openstack.cloud.role_assignment:
    auth: "{{ os_glance_cloud_auth }}"
    user: glance
    role: reader
    system: all
    state: present
  delegate_to: localhost
  become: false

- name: "Create glance service"
  openstack.cloud.catalog_service:
    auth: "{{ os_glance_cloud_auth }}"
    state: present
    name: glance
    type: image
    description: OpenStack Image Service
  delegate_to: localhost
  become: false

- name: Create endpoint service for glance
  openstack.cloud.endpoint:
    auth: "{{ os_glance_cloud_auth }}"
    service: glance
    endpoint_interface: "{{ item.interface }}"
    url: "{{ item.url }}"
    region: "{{ item.region }}"
    state: present
  loop:
    - interface: admin
      url: http://10.0.0.50:9292
      region: Nation1
    - interface: internal
      url: http://10.0.0.50:9292
      region: Nation1
    - interface: public
      url: http://10.0.0.50:9292
      region: Nation1
  delegate_to: localhost
  become: false
