---
- name: "Prefetch"
  ansible.builtin.include_tasks:
    file: prefetch.yml
  run_once: true

- name: "Config openstack service"
  ansible.builtin.include_tasks:
    file: config_os.yml
  run_once: true

- name: "Intall glance"
  apt:
    name: "glance"
    state: present
  become: true

- name: "Push config"
  ansible.builtin.template:
    src: "glance-api.conf.j2"
    dest: "/etc/glance/glance-api.conf"
    owner: "glance"
    group: "glance"
    mode: "0640"
  become: true

- name: "Check if glance was already bootstrapped from database"
  # check if tables exist in database with ansible module
  mysql_query:
    login_db: "{{ os_glance_db_name }}"
    login_host: "{{ os_glance_db_host }}"
    login_user: "{{ os_glance_db_user }}"
    login_password: "{{ os_glance_db_pass }}"
    query: show tables
  register: "glance_db_info"

- name: "debug"
  ansible.builtin.debug:
    msg: "{{ glance_db_info.query_result.0 | length  == 0 }}"

- name: Run glance database sync
  command: su -s /bin/sh -c "glance-manage db_sync" glance
  register: glance_db_sync_check
  failed_when: "glance_db_sync_check.rc == 1"
  changed_when: "glance_db_sync_check.rc not in [2, 3, 4]"
  when: glance_db_info.query_result.0 | length  == 0
  become: true

- name: "Restart glance"
  service:
    name: "glance-api"
    state: "restarted"
    enabled: true
  become: true